### ISSUE TITLE
Polestar_api integration fails to load after upgrading HA to 2025.10.0 (frontend 20251001.0)

### ISSUE THREAD

**Issue by TrondKjeldas** [pypolestar/polestar_api#378]
## The problem

The integration fails to load.

## Environment

Polestar_api 1.17.0
HA Core 2025.10.0
HA Frontend 20251001.0
Raspberry PI4, Debian GNU/Linux 12

## Traceback/Error logs

```
2025-10-21 19:23:57.006 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Polestar EV for trond@kjeldas.no for polestar_api
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/pypolestar/api.py", line 229, in _query_graph_ql
    result = await self.gql_session.execute(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/gql/client.py", line 1640, in execute
    raise TransportQueryError(
    ...<4 lines>...
    )
gql.transport.exceptions.TransportQueryError: {'path': None, 'locations': [{'line': 12, 'column': 7, 'sourceName': None}], 'message': "Validation error of type FieldUndefined: Field 'images' in type 'Content' is undefined @ 'getConsumerCarsV2/content/images'"}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 761, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/polestar_api/__init__.py", line 43, in async_setup_entry
    await api_client.async_init()
  File "/usr/local/lib/python3.13/site-packages/pypolestar/api.py", line 70, in async_init
    if not (car_data := await self._get_all_vehicles_data(verbose=verbose)):
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pypolestar/api.py", line 197, in _get_all_vehicles_data
    result = await self._query_graph_ql(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/pypolestar/api.py", line 241, in _query_graph_ql
    raise PolestarApiException from exc
pypolestar.exceptions.PolestarApiException

```

**Comment by untruenorth** [comment]
Same issue here, same logs also.

These are my versions, for what it's worth given this looks like it _might_ be widespread: 
Core: 2025.10.3
Supervisor: 2025.10.0
Operating System: 16.2
Frontend: 20251001.4
